name: Theme Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Theme Check
        uses: shopify/theme-check-action@v2
